from __future__ import annotations

import unittest

import missionforge


class PublicApiBoundaryTests(unittest.TestCase):
    def test_package_root_is_the_programmer_kernel_surface(self) -> None:
        expected = {
            "ACKS_REF",
            "AGENT_EVENTS_REF",
            "AgentEvent",
            "AgentEventKind",
            "ArtifactRef",
            "ContractClause",
            "ContractValidationError",
            "ContextSummaryArtifact",
            "ContextSummaryKind",
            "ContextSummarySource",
            "CapabilityGrant",
            "DEFAULT_PROGRESS_REF",
            "EvidenceLedger",
            "EvidenceRecord",
            "EvidenceRef",
            "ExtensionAdapterMode",
            "ExtensionCapability",
            "ExtensionCompileReport",
            "ExtensionGrant",
            "ExtensionLoadRecord",
            "ExtensionLoadReport",
            "ExtensionLock",
            "ExtensionLockEntry",
            "FileEvidenceStore",
            "FileInteractionPort",
            "FinalPackage",
            "HostSandboxRunner",
            "InMemoryEvidenceStore",
            "InteractionDelivery",
            "InteractionVisibility",
            "JudgeRubric",
            "MissionForgeError",
            "NetworkPolicy",
            "PermissionManifest",
            "ProgressEvent",
            "ProgressStreamGrant",
            "ProgressStreamMount",
            "ProgressStreamWriter",
            "PiWorkerCall",
            "PiWorkerCallAdapter",
            "PiWorkerCallResult",
            "PiWorkerCallResultStatus",
            "PiWorkerCallRole",
            "ProductCompileStatus",
            "ProductIntegration",
            "ProductTaskContractCompileResult",
            "ReadGate",
            "Ref",
            "SandboxMode",
            "SandboxProfile",
            "ToolGateway",
            "ToolGatewayRequest",
            "ToolGatewayResult",
            "TaskContract",
            "TaskContractRevision",
            "USER_EVENTS_REF",
            "UserEvent",
            "UserEventAck",
            "UserEventKind",
            "WorkerBrief",
            "WriteGate",
            "WorkspacePolicy",
            "assert_refs_only_payload",
            "append_progress_event",
            "build_judge_rubric",
            "build_worker_brief",
            "compile_extension_lock",
            "create_capability_grant",
            "create_default_piworker_adapter",
            "create_sandbox_profile_from_workspace",
            "project_judge_rubric",
            "project_worker_brief",
            "read_progress_events",
            "render_progress_event",
            "read_extension_lock",
            "replay_decision_ledger",
            "run_piworker_call",
            "stable_json_hash",
            "stream_progress",
            "validate_ref",
            "verify_extension_lock",
            "write_extension_lock",
            "extension_load_report_from_lock",
        }

        self.assertEqual(set(missionforge.__all__), expected)
        for symbol in expected:
            self.assertTrue(hasattr(missionforge, symbol), symbol)

    def test_package_root_does_not_export_internal_or_high_level_surfaces(self) -> None:
        forbidden = {
            "ActiveMissionContract",
            "AgentExecutionPacket",
            "AgentExecutionReport",
            "AgenticFlowRunner",
            "AgenticFlowStatus",
            "AttemptInputManifest",
            "CapabilityProfile",
            "ContractManifest",
            "DecisionLedgerEventKind",
            "ExecutionReport",
            "ExpandedMission",
            "FrontDesk",
            "FrozenMissionContract",
            "JudgePacket",
            "JudgeReport",
            "MetricEvent",
            "MissionIR",
            "MissionResult",
            "MissionRevision",
            "MissionRunAudit",
            "MissionRuntime",
            "PiAgentRuntimeAdapter",
            "PiWorkerRuntimeFactory",
            "ProfilePack",
            "RepairBrief",
            "RepairTicket",
            "RevisionAppliedRecord",
            "RevisionPendingRecord",
            "RuntimeContractView",
            "RuntimeEngine",
            "TaskRevisionDecision",
            "TaskRevisionRequest",
            "Verifier",
            "WorkUnitCompiler",
            "WorkUnitContract",
            "WorkUnitHarness",
            "WorkerInvocation",
            "WorkerResult",
            "apply_mission_revision",
            "build_run_audit",
            "expand_mission",
            "freeze_mission",
            "pi_agent_runtime",
            "piworker",
            "run_repair_directive_with_default_piworker",
            "run_revision_draft_with_default_piworker",
            "TaskContractFlowPreset",
            "create_default_task_contract_flow",
        }

        for symbol in forbidden:
            self.assertNotIn(symbol, missionforge.__all__)
            self.assertFalse(hasattr(missionforge, symbol), symbol)


if __name__ == "__main__":
    unittest.main()
