"""MissionForge programmer kernel API.

The package root intentionally exposes only the small, orthogonal surface a
programmer needs to embed bounded PiWorker/LLM calls in ordinary Python
systems. Product integrations, host shells, and frozen legacy tools live
outside the root surface.
"""

from .decision_ledger import FinalPackage, replay_decision_ledger
from .contracts import (
    ContractValidationError,
    MissionForgeError,
    Ref,
    assert_refs_only_payload,
    stable_json_hash,
    validate_ref,
)
from .context_summary import (
    ContextSummaryArtifact,
    ContextSummaryKind,
    ContextSummarySource,
)
from .artifacts import (
    ArtifactMaterializationState,
    ArtifactRecord,
    ArtifactStore,
    ArtifactVersionRef,
    FileArtifactStore,
    InMemoryArtifactStore,
)
from .evidence import ArtifactRef, EvidenceRef
from .evidence_store import EvidenceLedger, EvidenceRecord, FileEvidenceStore, InMemoryEvidenceStore
from .extensions import (
    ExtensionCompileReport,
    ExtensionLoadRecord,
    ExtensionLoadReport,
    ExtensionLock,
    ExtensionLockEntry,
    compile_extension_lock,
    extension_load_report_from_lock,
    read_extension_lock,
    verify_extension_lock,
    write_extension_lock,
)
from .interaction import (
    AGENT_EVENTS_REF,
    ACKS_REF,
    USER_EVENTS_REF,
    AgentEvent,
    AgentEventKind,
    FileInteractionPort,
    InteractionDelivery,
    InteractionVisibility,
    UserEvent,
    UserEventAck,
    UserEventKind,
)
from .runtime_control import (
    CapabilityGrant,
    HostSandboxRunner,
    SandboxMode,
    SandboxProfile,
    ToolGateway,
    ToolGatewayRequest,
    ToolGatewayResult,
    create_capability_grant,
    create_sandbox_profile_from_workspace,
)
from .permissions import ReadGate, WriteGate
from .piworker_call import (
    PiWorkerCall,
    PiWorkerCallResult,
    PiWorkerCallResultStatus,
    PiWorkerCallRole,
)
from .piworker_runtime import (
    PiWorkerCallAdapter,
    create_default_piworker_adapter,
    run_piworker_call,
)
from .product_integration import (
    ProductCompileStatus,
    ProductIntegration,
    ProductTaskContractCompileResult,
)
from .progress_stream import (
    DEFAULT_PROGRESS_REF,
    ProgressEvent,
    ProgressStreamMount,
    ProgressStreamWriter,
    append_progress_event,
    read_progress_events,
    render_progress_event,
    stream_progress,
)
from .task_contract import (
    ContractClause,
    ExtensionAdapterMode,
    ExtensionCapability,
    ExtensionGrant,
    NetworkPolicy,
    PermissionManifest,
    ProgressStreamGrant,
    TaskContract,
    TaskContractRevision,
    WorkspacePolicy,
)
from .task_projection import (
    JudgeRubric,
    WorkerBrief,
    build_judge_rubric,
    build_worker_brief,
    project_judge_rubric,
    project_worker_brief,
)

__all__ = [
    "ArtifactRef",
    "ArtifactMaterializationState",
    "ArtifactRecord",
    "ArtifactStore",
    "ArtifactVersionRef",
    "AGENT_EVENTS_REF",
    "ACKS_REF",
    "AgentEvent",
    "AgentEventKind",
    "ContractClause",
    "ContractValidationError",
    "ContextSummaryArtifact",
    "ContextSummaryKind",
    "ContextSummarySource",
    "DEFAULT_PROGRESS_REF",
    "EvidenceLedger",
    "EvidenceRecord",
    "EvidenceRef",
    "ExtensionAdapterMode",
    "ExtensionCapability",
    "ExtensionCompileReport",
    "ExtensionGrant",
    "ExtensionLoadRecord",
    "ExtensionLoadReport",
    "ExtensionLock",
    "ExtensionLockEntry",
    "FileEvidenceStore",
    "FileArtifactStore",
    "FileInteractionPort",
    "FinalPackage",
    "CapabilityGrant",
    "HostSandboxRunner",
    "InMemoryEvidenceStore",
    "InMemoryArtifactStore",
    "InteractionDelivery",
    "InteractionVisibility",
    "JudgeRubric",
    "MissionForgeError",
    "NetworkPolicy",
    "PermissionManifest",
    "SandboxMode",
    "SandboxProfile",
    "PiWorkerCall",
    "PiWorkerCallAdapter",
    "PiWorkerCallResult",
    "PiWorkerCallResultStatus",
    "PiWorkerCallRole",
    "ProductCompileStatus",
    "ProductIntegration",
    "ProductTaskContractCompileResult",
    "ProgressEvent",
    "ProgressStreamMount",
    "ProgressStreamGrant",
    "ProgressStreamWriter",
    "ReadGate",
    "Ref",
    "ToolGateway",
    "ToolGatewayRequest",
    "ToolGatewayResult",
    "TaskContract",
    "TaskContractRevision",
    "USER_EVENTS_REF",
    "UserEvent",
    "UserEventAck",
    "UserEventKind",
    "WorkerBrief",
    "WriteGate",
    "WorkspacePolicy",
    "assert_refs_only_payload",
    "append_progress_event",
    "build_judge_rubric",
    "build_worker_brief",
    "compile_extension_lock",
    "create_capability_grant",
    "create_default_piworker_adapter",
    "create_sandbox_profile_from_workspace",
    "project_judge_rubric",
    "project_worker_brief",
    "read_progress_events",
    "render_progress_event",
    "read_extension_lock",
    "replay_decision_ledger",
    "run_piworker_call",
    "stable_json_hash",
    "stream_progress",
    "validate_ref",
    "verify_extension_lock",
    "write_extension_lock",
    "extension_load_report_from_lock",
]
